parallel-jobs = 1

cli-source = "revanced/revanced-cli"
patches-source = "revanced/revanced-patches"
integrations-source = "revanced/revanced-integrations"

cli-version = "latest"
patches-version = "latest"

[TikTok]
enabled = true
# cli-version = "latest"
# patches-version = "v5.7.2"
build-mode = "apk"
version = "auto"
arch = "all"
apkmirror-dlurl = "https://apkmirror.com/apk/tiktok-pte-ltd/tik-tok/"
# uptodown-dlurl = "https://tik-tok.en.uptodown.com/android"
included-patches = "'Feed filter' 'Remember clear display' 'Downloads' 'Show seekbar' 'Playback speed' 'Disable login requirement' 'Fix Google login' 'Settings' 'SIM spoof'"
exclusive-patches = true

[TikTok-Musically]
enabled = false
# cli-version = "latest"
# patches-version = "v5.7.2"
build-mode = "apk"
version = "auto"
arch = "all"
apkmirror-dlurl = "https://apkmirror.com/apk/tiktok-pte-ltd/tik-tok-including-musical-ly/"
# uptodown-dlurl = "https://tiktok.en.uptodown.com/android"
included-patches = "'Feed filter' 'Remember clear display' 'Downloads' 'Show seekbar' 'Playback speed' 'Disable login requirement' 'Fix Google login' 'Settings' 'SIM spoof'"
exclusive-patches = true
